// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvcDay09LabCF.Models;

#nullable disable

namespace TvcDay09LabCF.Migrations
{
    [DbContext(typeof(TvcDay09LabCFContext))]
    partial class TvcDay09LabCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TvcDay09LabCF.Models.LoaiSanPham", b =>
                {
                    b.Property<long>("IDLoaiSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDLoaiSanPham"));

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDLoaiSanPham");

                    b.HasIndex("MaLoai")
                        .IsUnique();

                    b.ToTable("TblLoaiSanPham");
                });

            modelBuilder.Entity("TvcDay09LabCF.Models.SanPham", b =>
                {
                    b.Property<long>("IDSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDSanPham"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LoaiSanPhamID")
                        .HasColumnType("bigint");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSanPham");

                    b.HasIndex("LoaiSanPhamID");

                    b.ToTable("tblSanPham");
                });

            modelBuilder.Entity("TvcDay09LabCF.Models.SanPham", b =>
                {
                    b.HasOne("TvcDay09LabCF.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPham")
                        .HasForeignKey("LoaiSanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("TvcDay09LabCF.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
